version: '3.8'
services:
  client:
    container_name: 'client'
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3002:3000"
    volumes: 
     - .:/app
    restart: always
    stdin_open: true

  test:
    container_name: 'test'
    build: 
      context: .
      dockerfile: Dockerfile-dev
    volumes: 
     - .:/app
    restart: always
    stdin_open: true
    command: npm test

