apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-discovery
  namespace: default
  uid: fce1b65d-501a-434d-8692-78db6ae765e9
  resourceVersion: '184662'
  generation: 2
  creationTimestamp: '2022-09-23T13:26:14Z'
  labels:
    app.kubernetes.io/component: discovery
    app.kubernetes.io/instance: basic
    app.kubernetes.io/managed-by: tikv-operator
    app.kubernetes.io/name: tikv-cluster
  annotations:
    deployment.kubernetes.io/revision: '1'
    tikv.org/last-applied-configuration: >-
      {"containers":[{"name":"discovery","image":"pingcap/tikv-operator:v0.1.0","command":["/usr/local/bin/pd-discovery"],"env":[{"name":"MY_POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"TZ","value":"UTC"}],"resources":{},"imagePullPolicy":"IfNotPresent"}],"serviceAccountName":"basic-discovery"}
    tikv.org/last-applied-podtemplate: >-
      {"containers":[{"name":"discovery","image":"pingcap/tikv-operator:v0.1.0","command":["/usr/local/bin/pd-discovery"],"env":[{"name":"MY_POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"TZ","value":"UTC"}],"resources":{},"imagePullPolicy":"IfNotPresent"}],"serviceAccountName":"basic-discovery"}
  ownerReferences:
    - apiVersion: tikv.org/v1alpha1
      kind: TikvCluster
      name: basic
      uid: 20c85519-dfcb-4e4a-96ff-0305af1a97d2
      controller: true
      blockOwnerDeletion: true
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: discovery
      app.kubernetes.io/instance: basic
      app.kubernetes.io/managed-by: tikv-operator
      app.kubernetes.io/name: tikv-cluster
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: discovery
        app.kubernetes.io/instance: basic
        app.kubernetes.io/managed-by: tikv-operator
        app.kubernetes.io/name: tikv-cluster
    spec:
      containers:
        - name: discovery
          image: pingcap/tikv-operator:v0.1.0
          command:
            - /usr/local/bin/pd-discovery
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: TZ
              value: UTC
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: basic-discovery
      serviceAccount: basic-discovery
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
