apiVersion: v1
kind: Service
metadata:
  name: basic-tikv-peer
  namespace: default
  uid: fafc7517-655b-41e8-81d0-ff813d5c864c
  resourceVersion: '184718'
  creationTimestamp: '2022-09-23T13:26:37Z'
  labels:
    app.kubernetes.io/component: tikv
    app.kubernetes.io/instance: basic
    app.kubernetes.io/managed-by: tikv-operator
    app.kubernetes.io/name: tikv-cluster
  annotations:
    tikv.org/last-applied-configuration: >-
      {"ports":[{"name":"peer","protocol":"TCP","port":20160,"targetPort":20160}],"selector":{"app.kubernetes.io/component":"tikv","app.kubernetes.io/instance":"basic","app.kubernetes.io/managed-by":"tikv-operator","app.kubernetes.io/name":"tikv-cluster"},"clusterIP":"None","publishNotReadyAddresses":true}
status:
  loadBalancer: {}
spec:
  ports:
    - name: peer
      protocol: TCP
      port: 20160
      targetPort: 20160
  selector:
    app.kubernetes.io/component: tikv
    app.kubernetes.io/instance: basic
    app.kubernetes.io/managed-by: tikv-operator
    app.kubernetes.io/name: tikv-cluster
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
