apiVersion: apps/v1
kind: Deployment
metadata:
  name: tikv-operator
  namespace: tikv-operator
  uid: 3465b236-afcb-4eaa-9fc6-b6ab2d6f53d3
  resourceVersion: '183699'
  generation: 1
  creationTimestamp: '2022-09-23T13:04:05Z'
  labels:
    app.kubernetes.io/instance: tikv-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tikv-operator
    app.kubernetes.io/version: v0.1.0
    helm.sh/chart: tikv-operator-v0.1.0
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: tikv-operator
    meta.helm.sh/release-namespace: tikv-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: tikv-operator
      app.kubernetes.io/name: tikv-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: tikv-operator
        app.kubernetes.io/name: tikv-operator
    spec:
      containers:
        - name: tikv-operator
          image: pingcap/tikv-operator:v0.1.0
          command:
            - /usr/local/bin/tikv-controller-manager
          args:
            - '--pd-discovery-image=pingcap/tikv-operator:v0.1.0'
            - '-v=2'
          ports:
            - name: http
              containerPort: 6060
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources: {}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: tikv-operator
      serviceAccount: tikv-operator
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
