apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: basic-tikv
  namespace: default
  uid: 9bfadb64-2679-4271-9513-27f22bf76de2
  resourceVersion: '184810'
  generation: 1
  creationTimestamp: '2022-09-23T13:26:37Z'
  labels:
    app.kubernetes.io/component: tikv
    app.kubernetes.io/instance: basic
    app.kubernetes.io/managed-by: tikv-operator
    app.kubernetes.io/name: tikv-cluster
  annotations:
    tikv.org/last-applied-configuration: >-
      {"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/component":"tikv","app.kubernetes.io/instance":"basic","app.kubernetes.io/managed-by":"tikv-operator","app.kubernetes.io/name":"tikv-cluster"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app.kubernetes.io/component":"tikv","app.kubernetes.io/instance":"basic","app.kubernetes.io/managed-by":"tikv-operator","app.kubernetes.io/name":"tikv-cluster"},"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"20180","prometheus.io/scrape":"true"}},"spec":{"volumes":[{"name":"annotations","downwardAPI":{"items":[{"path":"annotations","fieldRef":{"fieldPath":"metadata.annotations"}}]}},{"name":"config","configMap":{"name":"basic-tikv","items":[{"key":"config-file","path":"tikv.toml"}]}},{"name":"startup-script","configMap":{"name":"basic-tikv","items":[{"key":"startup-script","path":"tikv_start_script.sh"}]}}],"containers":[{"name":"tikv","image":"pingcap/tikv:v4.0.0","command":["/bin/sh","/usr/local/bin/tikv_start_script.sh"],"ports":[{"name":"server","containerPort":20160,"protocol":"TCP"}],"env":[{"name":"NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"CLUSTER_NAME","value":"basic"},{"name":"HEADLESS_SERVICE_NAME","value":"basic-tikv-peer"},{"name":"CAPACITY","value":"0"},{"name":"TZ"}],"resources":{},"volumeMounts":[{"name":"annotations","readOnly":true,"mountPath":"/etc/podinfo"},{"name":"tikv","mountPath":"/var/lib/tikv"},{"name":"config","readOnly":true,"mountPath":"/etc/tikv"},{"name":"startup-script","readOnly":true,"mountPath":"/usr/local/bin"}],"imagePullPolicy":"IfNotPresent","securityContext":{"privileged":false}}],"restartPolicy":"Always"}},"volumeClaimTemplates":[{"metadata":{"name":"tikv","creationTimestamp":null},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}},"status":{}}],"serviceName":"basic-tikv-peer","podManagementPolicy":"Parallel","updateStrategy":{"type":"RollingUpdate","rollingUpdate":{"partition":1}}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: tikv
      app.kubernetes.io/instance: basic
      app.kubernetes.io/managed-by: tikv-operator
      app.kubernetes.io/name: tikv-cluster
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: tikv
        app.kubernetes.io/instance: basic
        app.kubernetes.io/managed-by: tikv-operator
        app.kubernetes.io/name: tikv-cluster
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '20180'
        prometheus.io/scrape: 'true'
    spec:
      volumes:
        - name: annotations
          downwardAPI:
            items:
              - path: annotations
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.annotations
            defaultMode: 420
        - name: config
          configMap:
            name: basic-tikv
            items:
              - key: config-file
                path: tikv.toml
            defaultMode: 420
        - name: startup-script
          configMap:
            name: basic-tikv
            items:
              - key: startup-script
                path: tikv_start_script.sh
            defaultMode: 420
      containers:
        - name: tikv
          image: pingcap/tikv:v4.0.0
          command:
            - /bin/sh
            - /usr/local/bin/tikv_start_script.sh
          ports:
            - name: server
              containerPort: 20160
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CLUSTER_NAME
              value: basic
            - name: HEADLESS_SERVICE_NAME
              value: basic-tikv-peer
            - name: CAPACITY
              value: '0'
            - name: TZ
          resources: {}
          volumeMounts:
            - name: annotations
              readOnly: true
              mountPath: /etc/podinfo
            - name: tikv
              mountPath: /var/lib/tikv
            - name: config
              readOnly: true
              mountPath: /etc/tikv
            - name: startup-script
              readOnly: true
              mountPath: /usr/local/bin
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: tikv
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: basic-tikv-peer
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 1
  revisionHistoryLimit: 10
