apiVersion: apps/v1
kind: Deployment
metadata:
  name: tidb-controller-manager
  namespace: tidb-admin
  uid: c4ac0e64-bc3a-44db-8abc-8aa881a67d32
  resourceVersion: '145013'
  generation: 1
  creationTimestamp: '2022-09-23T19:58:00Z'
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-v1.3.8
  annotations:
    deployment.kubernetes.io/revision: '1'
    meta.helm.sh/release-name: tidb-operator
    meta.helm.sh/release-namespace: tidb-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-manager
      app.kubernetes.io/instance: tidb-operator
      app.kubernetes.io/name: tidb-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/instance: tidb-operator
        app.kubernetes.io/name: tidb-operator
    spec:
      containers:
        - name: tidb-operator
          image: pingcap/tidb-operator:v1.3.8
          command:
            - /usr/local/bin/tidb-controller-manager
            - '-tidb-backup-manager-image=pingcap/tidb-backup-manager:v1.3.8'
            - '-tidb-discovery-image=pingcap/tidb-operator:v1.3.8'
            - '-cluster-scoped=true'
            - '-cluster-permission-node=true'
            - '-cluster-permission-pv=true'
            - '-cluster-permission-sc=true'
            - '-auto-failover=true'
            - '-pd-failover-period=5m'
            - '-tikv-failover-period=5m'
            - '-tiflash-failover-period=5m'
            - '-tidb-failover-period=5m'
            - '-dm-master-failover-period=5m'
            - '-dm-worker-failover-period=5m'
            - '-v=2'
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: TZ
              value: UTC
          resources:
            requests:
              cpu: 80m
              memory: 50Mi
          livenessProbe:
            tcpSocket:
              port: 6060
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: tidb-controller-manager
      serviceAccount: tidb-controller-manager
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
