[package]
name = "data-indept"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kernel32-sys = "0.2.2"
piston2d-graphics = "0.42.0"
piston_window = "0.124.0"
rand = "0.8.5"
winapi = "0.3.9"
