[package]
name = "blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
crossbeam = "0.8.2"
parking_lot = "0.12.1"
itertools = "0.10.3"