import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react";

import Header from "../components/Header";
import Card from "../components/Card";
import Form from "../components/Form";
import { getAllCampaigns } from "../solana";

const Home: NextPage = () => {
    const [route, setRoute] = useState(0);
    const [cards, setCards] = useState([]);
    useEffect(() => {
      getAllCampaigns().then((val) => {
        setCards(val);
        console.log(val);
      });
    }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="ui container">
          <Header setRoute={setRoute} />
          {route === 0 ? (
            <div>
              {cards.map((e, idx) => (
                <Card
                  key={e.pubId.toString()}
                  data={{
                    title: e.name,
                    description: e.description,
                    amount: e.amount_donated.toString(),
                    image: e.image_link,
                    id: e.pubId,
                  }}
                  setCards={setCards}
                />
              ))}
            </div>
          ) : (
            <Form
              setRoute={(e) => {
                setRoute(e);
                getAllCampaigns().then((val) => {
                  setCards(val);
                });
              }}
            />
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export default Home
